### ISSUE TITLE
ImportError: No module named transloadit

### ISSUE THREAD

**Issue by XabierGallardo** [Missing-Tech/Vinyl-Gif-Maker#1]
Hi, after following the tutorial, I found the next error while trying to execute
`python spinning_vinyl.py`

It returns
`Traceback (most recent call last):`
`  File "vinyl.py", line 2, in <module>`
`    from transloadit import client
ImportError: No module named transloadit`

I did previously
`pip install pytransloadit`
`from transloadit import client`

So I don't know what cause the issue
Kind regards!

**Comment by joegrabski** [comment]
Hi!

Using a fresh install of python `3.11.1` and running the pip install commands for all the packages, I don't get this error. What do you see when you run `pip install pytransloadit`?

**Comment by XabierGallardo** [comment]
Hi! It seems it's already installed. I had no problem doing the pip install commands either

```sh
Requirement already satisfied: pytransloadit in /usr/local/lib/python3.8/dist-packages (0.2.1)
Requirement already satisfied: requests>=2.18.4 in /usr/lib/python3/dist-packages (from pytransloadit) (2.22.0)
Requirement already satisfied: tuspy>=0.2.3 in /usr/local/lib/python3.8/dist-packages (from pytransloadit) (1.0.0)
Requirement already satisfied: six>=1.11.0 in /usr/lib/python3/dist-packages (from pytransloadit) (1.14.0)
Requirement already satisfied: tinydb>=3.5.0 in /usr/local/lib/python3.8/dist-packages (from tuspy>=0.2.3->pytransloadit) (4.7.0)
Requirement already satisfied: future>=0.16.0 in /usr/local/lib/python3.8/dist-packages (from tuspy>=0.2.3->pytransloadit) (0.18.2)
Requirement already satisfied: aiohttp>=3.6.2 in /usr/local/lib/python3.8/dist-packages (from tuspy>=0.2.3->pytransloadit) (3.8.3)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.8/dist-packages (from aiohttp>=3.6.2->tuspy>=0.2.3->pytransloadit) (6.0.4)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.8/dist-packages (from aiohttp>=3.6.2->tuspy>=0.2.3->pytransloadit) (1.3.3)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.8/dist-packages (from aiohttp>=3.6.2->tuspy>=0.2.3->pytransloadit) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.8/dist-packages (from aiohttp>=3.6.2->tuspy>=0.2.3->pytransloadit) (1.3.1)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp>=3.6.2->tuspy>=0.2.3->pytransloadit) (2.1.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp>=3.6.2->tuspy>=0.2.3->pytransloadit) (1.8.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp>=3.6.2->tuspy>=0.2.3->pytransloadit) (22.2.0)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp>=3.6.2->tuspy>=0.2.3->pytransloadit) (2.8)

```

Running the script with python 3 seems to give the same error

```sh
Traceback (most recent call last):
  File "spinning_vinyl.py", line 2, in <module>
    from transloadit import client
ImportError: No module named transloadit
```

**Comment by joegrabski** [comment]
Is it possible that you have multiple python instances installed? I wonder if the pytransloadit package is installed on a different instance to the one that you're running the program from.
